name: Workflows to call when push command is detecte on the repo

on: push

# Permissions that the job has
permissions:
  actions: read
  contents: write
  pull-requests: write
  statuses: read

jobs:
  update-semantic_version:
    uses: vegastyle/vega-versioning-workflow/.github/workflows/update_version_workflow.yml@v1.1.1